### ISSUE TITLE
Angular app refuses to connect to Express API

### ISSUE THREAD

**Issue by jerrywardlow** [gangachris/mean-docker#1]
The Angular app does not function out of the box. Upon cloning the repo and running `docker-compose up`, the app receives a connection error when issuing a GET request to `localhost:3000/users`.

Ubuntu 16.04
Docker 1.12.1
Docker Compose 1.9.0
Google Chrome 55.0.2883.87 m (64-bit)

**Comment by jerrywardlow** [comment]
Tested against the following server as well with the same results:

Centos 7
Docker 1.12.5
Docker Compose 1.9.0
Microsoft Edge 38.14393.0.0

**Comment by gangachris** [comment]
Hi @jerrywardlow Is there an expressjs error, when you run this? Something like `express exited with status 254` (not 0)
